---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      # - id: check-json
      - id: check-merge-conflict
      # - id: check-toml
      # - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      # - id: sort-simple-yaml
      - id: trailing-whitespace
        # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      # - id: name-tests-test
      # - id: requirements-txt-fixer
  # General
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/rkm/pre-commit-nocommit
    rev: "b4dc8cafaf3ed98ffe7000415279c589c097c7bb"
    hooks:
      - id: nocommit
        exclude: |
          (?x)^(
            .pre-commit-config.yaml|
            meta/pre-commit-config-base.yaml|
          )$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          [
            --ignore-words,
            .meta/codespell-ignores,
            --exclude-file,
            .meta/codespell-excludes,
            --ignore-regex,
            '\Whttps?://\S*',
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        args: [--config, .meta/prettierrc.yml]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-c, .meta/yamllint.yaml]
  # Shell
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
  # Python
  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v1.11.0
  #   hooks:
  #       - id: setup-cfg-fmt
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-no-log-warn
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [--py36-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        additional_dependencies: [pep8-naming]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        args: [--config-file, .meta/mypy.ini]
  - repo: https://github.com/psf/black
    rev: "21.9b0"
    hooks:
      - id: black
        language_version: python38
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-assert-msg, flake8-bugbear, pep8-naming]
        args: [--config, .meta/flake8.conf]
