repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
- repo: 'https://github.com/codespell-project/codespell.git'
  rev: v1.16.0
  hooks:
    - id: codespell
