---
# See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix, --indent=4]
      - id: sort-simple-yaml
      - id: trailing-whitespace
        # Python
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
    # General
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/codespell-project/codespell
    rev: ""
    hooks:
      - id: codespell
        args:
          [
            --ignore-words,
            .meta/codespell-ignores,
            --ignore-regex,
            '\Whttps?://\S*',
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ""
    hooks:
      - id: prettier
        args: [--config, .meta/prettierrc.yml]
  - repo: https://github.com/adrienverge/yamllint
    rev: ""
    hooks:
      - id: yamllint
        args: [-c, .meta/yamllint.yaml]
    # Python
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: ""
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: ""
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-no-log-warn
  - repo: https://github.com/asottile/reorder_python_imports
    rev: ""
    hooks:
      - id: reorder-python-imports
        args: [--py36-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: ""
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: ""
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/yesqa
    rev: ""
    hooks:
      - id: yesqa
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ""
    hooks:
      - id: mypy
        args: [--config-file, .meta/mypy.ini]
  - repo: https://github.com/psf/black
    rev: ""
    hooks:
      - id: black
        language_version: python38
  - repo: https://gitlab.com/pycqa/flake8
    rev: ""
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-assert-msg]
        args: [--config, .meta/flake8.conf]
    # Ansible
  - repo: https://github.com/ansible/ansible-lint.git
    rev: ""
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
