#!/usr/bin/env bash

### Included from https://github.com/rkm/dotfiles/blob/master/linux/.bash_aliases ###

alias grep='grep --color=auto --line-buffered'
alias ls='ls -lap --color=auto --group-directories-first'
alias ll='ls'
alias diff='diff -u'
alias cols='watch tput cols'
alias watch='watch -c'
alias path='echo -e ${PATH//:/\\n}'
alias utop='top -u $USER'
alias clock='watch -n0.1 '\''figlet -ctkf big "$(date +%H:%M:%S)"'\'''

alias wget='wget --hsts-file=$XDG_CACHE_HOME/wget-hsts'

alias gdc='git diff --cached'

alias ss='sudo systemctl'

alias weechat='weechat -d $XDG_CONFIG_HOME/weechat'

alias tf=terraform

alias clean_ssh="SSH_AUTH_SOCK= TERM=xterm ssh"

if [ -d ~/opt/maven ]; then
    function mvn () {
        ~/opt/maven/bin/mvn \
            --no-transfer-progress \
            --settings "$XDG_CONFIG_HOME"/maven/settings.xml \
            "$@"
    }
    export -f mvn
fi
