#!/usr/bin/env bash

### Included from https://github.com/rkm/dotfiles/blob/master/linux/.bashrc ###

# NOTE: If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

LS_COLORS=${LS_COLORS}:'di=4;37:'
export LS_COLORS

shopt -s checkwinsize
shopt -s globstar
set -o vi

export EDITOR=vim
export VISUAL=vim

# Simplified settings for teaching
if [[ -n "${TEACH:=}" ]]; then
    unset PROMPT_COMMAND
    export PS1="[\u@\h \W]\\$ "
    alias python=python3
    return 0
fi

function timer_start {
  timer=${timer:-${SECONDS}}
}
trap 'timer_start' DEBUG

function timer_stop {
  timer_show=$(( SECONDS - timer ))
  unset timer
}

export PS1='\n\[$(printf "\\u2500%.0s" $(seq $(tput cols)))\]\n\[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] `date +%H:%M:%S%Z` ${timer_show}s ${RC} ${VENV_PROMPT}\n> '
function prompt_command {

    RC="$?"

    if \
        [[ -d .git ]] &&
        [[ ! -x .git/hooks/pre-commit ]] &&
        [[ -e .pre-commit-config.yaml ]] &&
        command -v pre-commit >& /dev/null
    then
        pre-commit install
    fi

    VENV_PROMPT=
    if [[ -n "${VIRTUAL_ENV}" ]]
    then
        VENV_PROMPT="(${VIRTUAL_ENV})"
    fi
    export VENV_PROMPT

    timer_stop
}
export PROMPT_COMMAND=prompt_command

# shellcheck source=linux/config/bash_aliases
[[ -f "${XDG_CONFIG_HOME:=}/bash_aliases" ]] && . "${XDG_CONFIG_HOME}/bash_aliases"
