
" Included from https://github.com/rkm/dotfiles/blob/master/linux/.vimrc

" XDG_DATA_HOME setup
set backupdir=$XDG_DATA_HOME/vim/backup
set directory=$XDG_DATA_HOME/vim/swap
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
set undodir=$XDG_DATA_HOME/vim/undo
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo

" Tabs
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

set noautoindent

" Don't auto-insert comments (on paste)
set formatoptions-=cro

" Column rulers
execute "set colorcolumn=80,88"
execute "highlight ColorColumn ctermbg=darkgrey"

" Trailing whitespace highlight
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" todo snippet
function TODO()
    return "# TODO(rkm " . strftime("%Y-%m-%d") . ")"
endfunction
iabbrev <expr> todo# TODO()

" dt snippet
function TODAY()
    return strftime("%Y-%m-%d")
endfunction
iabbrev <expr> dt# TODAY()

" turn hybrid line numbers on
set number relativenumber

" Remap Ctrl-W to Ctrl-E
nnoremap <C-e> <C-w>

" Misc.
set autoread
set pastetoggle=<F2>

set wrap
set linebreak

" Emoji shortcuts
ab :plus: ➕
ab :check: ✅
ab :cross: ❌
