#!/usr/bin/bash

. ~/.profile

file="/home/rkm/.au.last.tmp"
if : \
    || [ ! -f "$file" ] \
    || [ "$file" -ot ~/.au.cron.log ] \
    && ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } \
    ; then
    echo Running au script
    touch $file
    nohup au &> /dev/null &
fi
