#!/usr/bin/bash

. ~/.profile

# https://www.putorius.net/lock-files-bash-scripts.html
if { set -C; 2>/dev/null >~/.au.lock; }; then
    trap "rm -f ~/.au.lock" EXIT
else
    echo "Lock file exists - not running"
    return
fi

file="/home/rkm/.au.last.tmp"
if : \
    || [ ! -f "$file" ] \
    || [ "$file" -ot ~/.au.cron.log ] \
    && ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } \
    ; then
    echo Running au script
    touch $file
    nohup au --tags boot &> /dev/null &
fi
