#!/usr/bin/env bash

### Included from https://github.com/rkm/dotfiles/blob/master/linux/.profile ###

# Default settings

export PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"

export BROWSER="lynx"
export EDITOR="vim"
export TERMINAL="bash"

export XDG_CACHE_HOME="$HOME/.cache"
mkdir -p "$XDG_CACHE_HOME"

export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"

export XDG_DATA_HOME="$HOME/.local/share"
mkdir -p "$XDG_DATA_HOME"

export INPUTRC="$XDG_CONFIG_HOME/inputrc"
export LESSHISTFILE="-"

home_bin="$HOME/bin"; [ -d "$home_bin" ] && export PATH="$home_bin:$PATH"
opt_bin="/opt/bin";   [ -d "$opt_bin" ] && export PATH="$opt_bin:$PATH"

# Program-specific settings

## Docker
# export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

## dotnet
if [ -x "$(command -v dotnet)" ]; then
    # https://github.com/dotnet/sdk/issues/9304
    dotnet_root=$(dirname "$(realpath "$(which dotnet)")")
    export DOTNET_ROOT=$dotnet_root
    export DOTNET_CLI_TELEMETRY_OPTOUT=1
    export PATH="$HOME/.dotnet:$PATH"
fi

# GitHub PAT
PAT_FILE="$XDG_CONFIG_HOME/GITHUB_PAT"
if [ -f "$PAT_FILE" ]; then
    GITHUB_TOKEN="$(cat "$PAT_FILE")"
    export GITHUB_TOKEN
fi

## Go
export GOPATH="$HOME/src/go"
go_bin="$GOPATH/bin"; [ -d "$go_bin" ] && export PATH="$go_bin:$PATH"

## Java
mvn_dir="$HOME/opt/maven/bin"; [ -d "$mvn_dir" ] && export PATH="$PATH:$mvn_dir"
java_home=$(readlink -m "$(readlink -f /usr/bin/java)/../../..")
[ -d "$java_home" ] && export JAVA_HOME="$java_home"

## JavaScript
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

## Lynx
export LYNX_CFG="$HOME/.config/lynx/lynx.cfg"
export LYNX_LSS="$HOME/.config/lynx/lynx.lss"

## Python
pythonrc="$XDG_CONFIG_HOME"/python_startup.py; [ -f "$pythonrc" ] && export PYTHONSTARTUP="$pythonrc"
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

## Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
cargo_bin="$XDG_DATA_HOME/cargo/bin"; [ -d "$cargo_bin" ] && export PATH="$cargo_bin:$PATH"

## SQLite
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"

## Stack
export STACK_ROOT="$XDG_DATA_HOME/stack"

## Vim
export VIMINIT=":source $XDG_CONFIG_HOME/vim/vimrc"
mkdir -p "$XDG_DATA_HOME"/vim/{backup,swap,undo,view}

## Weechat
export WEECHAT_HOME="$XDG_CONFIG_HOME"/weechat

## Virtualenv
# NOTE(rkm 2021-10-25) Build our own prompt
export VIRTUAL_ENV_DISABLE_PROMPT=true
export VIRTUALENV_ACTIVATORS=bash

# Finally, source bashrc
# shellcheck source=linux/config/bashrc
[ -f "$XDG_CONFIG_HOME/bashrc" ] && . "$XDG_CONFIG_HOME/bashrc"
