#!/usr/bin/env bash

### Included from https://github.com/rkm/dotfiles/blob/master/linux/.profile ###

# TODO: export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"

# Default settings

export BROWSER="lynx"
export EDITOR="vim"
export TERMINAL="bash"

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export INPUTRC="$XDG_CONFIG_HOME/inputrc"
export LESSHISTFILE="-"

export PATH="/opt/bin:$PATH"
export PATH="/home/rkm/.local/bin:$PATH"

# Program-specific settings

## Docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

## Dotnet
export DOTNET_CLI_TELEMETRY_OPTOUT=1
# https://github.com/dotnet/sdk/issues/9304
dotnet_root=$(dirname "$(realpath "$(which dotnet)")")
[ -x "$(command -v dotnet)" ] && export DOTNET_ROOT=$dotnet_root

## Go
export GOPATH="$HOME/dev/go"
export PATH="$GOPATH/bin:$PATH"

## Java
mvn_dir="$HOME/opt/maven/bin"; [ -d "$mvn_dir" ] && export PATH="$PATH:$mvn_dir"
java_home=$(readlink -m "$(readlink -f /usr/bin/java)/../..")
[ -f /usr/bin/java ] && export JAVA_HOME=$java_home

## JavaScript
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

## Lynx
export LYNX_CFG="$HOME/.config/lynx/lynx.cfg"
export LYNX_LSS="$HOME/.config/lynx/lynx.lss"

## Python
pythonrc="$XDG_CONFIG_HOME"/python_startup.py
[ -f "$pythonrc" ] && export PYTHONSTARTUP=$pythonrc
export IPYTHONDIR="$XDG_CONFIG_HOME/jupyter"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

## Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export PATH="/home/rkm/.local/share/cargo/bin:$PATH"

## SQLite
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"

## Stack
export STACK_ROOT="$XDG_DATA_HOME/stack"

## Vim
export VIMINIT=":source $XDG_CONFIG_HOME/vim/vimrc"

## Weechat
export WEECHAT_HOME="$XDG_CONFIG_HOME"/weechat


# Finally, source bashrc
# shellcheck source=linux/bashrc
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
